@openmediaserver.net_HostAddress = http://localhost:5265

### Get All Media
GET {{openmediaserver.net_HostAddress}}/api/media
Accept: application/json

###

### Get Media Item by ID
GET {{openmediaserver.net_HostAddress}}/api/media/media-id-here
Accept: application/json

###

### Stream Media with Range Support
GET {{openmediaserver.net_HostAddress}}/api/stream/media-id-here
Accept: application/json

###